version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules  # Prevents overwriting container's node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:etracker@db:5432/etrack

  db:
    image: postgres:15
    container_name: etrack-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: etracker
      POSTGRES_DB: etrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
